apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: "http_proxy"
                    value: "http://10.193.21.116:8080"
                  - name: "https_proxy"
                    value: "http://10.193.21.116:8080"
                  - name: "no_proxy"
                    value: "localhost,127.0.0.1,10.0.0.0/8,172.18.0.0/16,.cluster.local.,.cluster.local,.svc,.flux-system"                    
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
